apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: argocd-metrics
  namespace: observability
  labels:
    app.kubernetes.io/part-of: platforminit
    platforminit.io/chapter: ch05
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - argocd-server
          - argocd-repo-server
          - argocd-application-controller
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
