apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zabbix
  namespace: operations
  labels:
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/part-of: platforminit-operations
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - zabbix.sysadminhomelab.hu
      secretName: zabbix-tls
  rules:
    - host: zabbix.sysadminhomelab.hu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zabbix-web
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openobserve
  namespace: operations
  labels:
    app.kubernetes.io/name: openobserve
    app.kubernetes.io/part-of: platforminit-operations
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - logs.sysadminhomelab.hu
      secretName: openobserve-tls
  rules:
    - host: logs.sysadminhomelab.hu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openobserve
                port:
                  number: 5080
