apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: observability
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.__BASE_DOMAIN__
  issuerRef:
    name: __CLUSTER_ISSUER__
    kind: ClusterIssuer
