apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: operations
  labels:
    app.kubernetes.io/name: zabbix-server
    app.kubernetes.io/part-of: platforminit-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_SERVER_HOST
              value: zabbix-postgres
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: zabbix-postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-postgres
                  key: POSTGRES_PASSWORD
          ports:
            - name: zabbix-trapper
              containerPort: 10051
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 700m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: operations
spec:
  selector:
    app.kubernetes.io/name: zabbix-server
  ports:
    - name: zabbix-trapper
      port: 10051
      targetPort: zabbix-trapper
